Update run_8xH20.sh
the previous backend will raise " TypeError: _write_item() missing 1 required positional argument: 'serialization_format' " , update to new compatible version.